### ISSUE TITLE
listen localhost only?

### ISSUE THREAD

**Issue by KlavsKlavsen** [saz/puppet-rsyslog#106]
I'd like to make rsyslog listen on localhost only.. so haproxy can log to it.

Something like this:
# Provides UDP syslog reception
$ModLoad imudp
$UDPServerAddress 127.0.0.1
$UDPServerRun 514

I'm not keen on just hacking rsyslog without upstreaming.. so I'm asking, would you prefer to add a "listenip" to rsyslog::server.. or perhaps a "listen_localhost" to the rsyslog::client ?

(if you at all want this option ofcourse :)

**Comment by robertdebock** [comment]
I would like a related feature; listening only on a certain address. Looking at the rsyslog configuration wiki: http://wiki.rsyslog.com/index.php/Very_simple_config_--_starting_point_for_modifications
There appears to be a parameter:
```
$UDPServerAddress 123.123.123.123
```

And there appears to be another parameter:
```
$TCPServerAddress 123.123.123.123
```

Am I missing something or is this not a feature at the moment?

**Comment by saz** [comment]
@KlavsKlavsen Your PR is merged
@robertdebock Please open a new issue (or even better, send in a pull request)
