### ISSUE TITLE
Adding custom rules - rsyslog load order

### ISSUE THREAD

**Issue by treydock** [saz/puppet-rsyslog#108]
Maybe I'm missing a key feature already provided by this module, but if I want to have all log messages from pulp go to a separate file I'd add the following to '/etc/rsyslog.d/pulp.conf'.

```
:programname, isequal, "pulp" -/var/log/pulp.log
& ~
```

That never gets picked up as /var/log/messages continues to contain the logs.

If I rename pulp.conf to 00_pulp.conf then all pulp messages go to /var/log/pulp.log but the timestamp format is not picking up that was defined in /etc/rsyslog.d/client.conf.  Is this a case that hasn't been built into the module yet?  It seems like the only way to cleanly work around this is to split the contents of client.conf into two separate files.  One is 00_client.conf that configures things like `ActionFileDefaultTemplate` and the remote logging, and the other being 99_local.conf that has the local log rules.

I'd be interested to know how others handle such cases using this module, or if a PR that splits the client configuration up into 2 files would be accepted.

**Comment by aamerik** [comment]
@treydock can you share the puppet code you would use to generate 

```
:programname, isequal, "pulp" -/var/log/pulp.log
& ~
```
I cant figure out how to do this using the module. Thank you

**Comment by treydock** [comment]
@aamerik Unfortunately because the load order is not right I left my pulp config out of Puppet.  My guess would be something like this would work

```puppet
rsyslog::snippet { 'pulp':
  content => ':programname, isequal, "pulp" -/var/log/pulp.log
& ~',
}
```

**Comment by treydock** [comment]
I am finally getting around to this and think I have a solution (untested, but will test to see how it works).

The `rsyslog::client` class gets a new parameter, `split_config` which defaults to `false` to maintain backwards compatibility and avoid people getting unexpected changes.  The `custom_config` behavior will be the same.  When `split_config` is false the `template` function is passed 3 values, `client_config.conf.erb`, `client_remote.conf.erb`, and `client_local.conf.erb`.  I took the current `client.conf.erb` and just split it into 3 files.

The new behavior is if `split_config` is `true`.  It will create `00_client.conf`, `50_remote.conf` and `99_local.conf`.  The goal is that someone can add a custom snippet that is prefixed in such a way to come before either the remote log lines or after the remote log lines but before the local lines.

This still a rough idea, so input is welcome.

**Comment by saz** [comment]
This should be resolved in the current master
