### ISSUE TITLE
Duplicate logging on el7

### ISSUE THREAD

**Issue by mdsummers** [saz/puppet-rsyslog#113]
On a base installation of CentOS 7 using this module and the following parameters, double logging can be seen under /var/log/messages.
```puppet
  class { 'rsyslog::client':
    log_local => true,
    log_auth_local => true,
    log_remote => false,
  }
```
Example:
```
$ logger test
```
yields
```
Oct 21 16:44:03 mad-west-vcs006 centos: test
Oct 21 16:44:03 mad-west-vcs006 centos: test
```
This seems to be something to do with the journal integration added in el7.

One of the configuration items in the stock config (removed under puppet) fixes this behaviour
```
# Turn off message reception via local log socket;
# local messages are retrieved through imjournal now.
$OmitLocalLogging on
```

Should this be made part of the stock config for el7?

**Comment by saz** [comment]
Any news on this?
