### ISSUE TITLE
Rsyslog (v8.4.2) service fails to start on Ubuntu 12.04

### ISSUE THREAD

**Issue by dduvnjak** [saz/puppet-rsyslog#125]
Steps to reproduce:  
Install latest stable rsyslog as described at http://www.rsyslog.com/ubuntu-repository/
then:
`puppet apply -e 'include rsyslog'`

After that, rsyslog service is not running on the system, and it cannot be started at all.

**Comment by saz** [comment]
This should be working in master now. I'll release a new module version to the forge soon.
