### ISSUE TITLE
The default template does not have option to send to ~

### ISSUE THREAD

**Issue by ARsenthil** [saz/puppet-rsyslog#133]
In some cases, we might need to redirect to ~ in order not to write the logs to /var/log/messages.
The default client template's pattern does not have this option.
Ex: if $syslogfacility-text == 'local6' then ~ 
If we donot mention the hostname or port , from the init.pp the default values are coming.
or else if we supply empty value, remotehost section is appending @:

**Comment by saz** [comment]
I'm open for suggestions to fix this.

**Comment by saz** [comment]
As there was no feedback, I'm closing this issue now. If this is still required, please open a new issue.
