### ISSUE TITLE
Receiving duplicate declaration when applying default module

### ISSUE THREAD

**Issue by mprinvale** [saz/puppet-rsyslog#135]
puppet master & client 3.7.3
ubuntu 14.04

default settings:
class { 'rsyslog::server':
    enable_udp                => true,
    enable_onefile            => false,
    server_dir                => '/mnt/log/',
    custom_config             => undef,
    high_precision_timestamps => false,
  }

Error:
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: Package[rsyslog-gnutls] is already declared in file /etc/puppet/modules/loggly/manifests/rsyslog.pp:60; cannot redeclare at /etc/puppet/modules/rsyslog/manifests/install.pp:29 on node redacted.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

This is my first submitted issue on github, if I left anything out or placed wrong please let me know so I can update/improve.

**Comment by saz** [comment]
This issue should be fixed in the current master and will be released soon.
