### ISSUE TITLE
TLS Authentication by Hostname

### ISSUE THREAD

**Issue by znorris** [saz/puppet-rsyslog#140]
I'm trying to get TLS working with the Papertrail logging service. They require authenticating by hostname. Currently the client.conf.erb template only allows for anonymous authentication. (https://github.com/saz/puppet-rsyslog/blob/55efaa5e8b3442bb118d301442657ff19ba22fad/templates/client.conf.erb#L39)

Would it be possible to add the ability to pass a different auth mode? For this example I'd need to pass `x509/name`, then also specify a value for `$ActionSendStreamDriverPermittedPeer`.

It would look like this:
```
$ActionSendStreamDriverAuthMode x509/name # authenticate by hostname
$ActionSendStreamDriverPermittedPeer *.papertrailapp.com
```

**Comment by saz** [comment]
Feel free to open a pull request and I'll be happy to merge this change
