### ISSUE TITLE
Hiera Support

### ISSUE THREAD

**Issue by discreet** [saz/puppet-rsyslog#147]
Would it be possible to implement Hiera support similar to what is implemented in your Sudo module? I was thinking it would be really useful to have that type of support to create include files in rsyslog.d.

**Comment by saz** [comment]
Sure, but if you have the time, feel free to send in a pull request :)

**Comment by rothgar** [comment]
+1 for this

**Comment by discreet** [comment]
I've had this implement in my environment for a little while now. I'll see if I can find some time between the holidays to get a PR submitted.

**Comment by rothgar** [comment]
That'd be great. Would save me some time. Do you have a fork/branch I could
look at? That'd probably be enough for me.

On Tuesday, December 22, 2015, Chris Pisano <notifications@github.com>
wrote:

> I've had this implement in my environment for a little while now. I'll see
> if I can find some time between the holidays to get a PR submitted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/saz/puppet-rsyslog/issues/147#issuecomment-166714317>.
>


-- 
Sent from my phone

**Comment by discreet** [comment]
I'll get a branch working for you next week (traveling for holidays in a couple hours). Currently I only have a modified clone in our internal repository at my company.

**Comment by janvonde** [comment]
+1

**Comment by rothgar** [comment]
ping @discreet for a branch with hiera support

**Comment by discreet** [comment]
Here is a branch with hiera support. It is untested in this module though. I took a closer look at the module we are using at it is the ghoneycutt module for rsyslog.

https://github.com/discreet/puppet-rsyslog/tree/hiera_support/

**Comment by shortspecialbus** [comment]
Is this likely to be merged into the main branch along with writing a bit of documentation?  Policy means I can't use it without that :(  I'm not comfortable enough with this to offer to help, sorry :(

**Comment by saz** [comment]
@shortspecialbus if I'm receiving a PR for this, I'll be happy to merge and release it.

**Comment by shortspecialbus** [comment]
That would be excellent, thanks!

-stefan

--  
Generic
Sent with Airmail

**Comment by kwisatz** [comment]
I know this has been a few months back, but I don't think there's been a PR and the above-mentioned repo no longer exists. However, unless I'm mistaken, with automatic hiera lookups, there's hiera support in each and every module out there.

Having this in one of the hiera data files works for me, for instance, just having `class { '::rsyslog::client': }` in the manifest:

```yaml
rsyslog::client::remote_servers:
  - host: graylog.myservers.com
    port: '5140'
    pattern: '*.*'
    format: 'RSYSLOG_SyslogProtocol23Format'
rsyslog::client::log_local: true
rsyslog::client::log_auth_local: true
```

**Comment by ubellavance** [comment]
@kwisatz it works, you're right.  But other things doesn't. Personnaly, I can't get imfile configs to work in hiera.  I'll create a different issue for that though.

**Comment by saz** [comment]
I think most of the things are working with automatic lookups, therefore I'll close this issue.
If there are things missing, please create a separate issue for your needs. Thanks!
