### ISSUE TITLE
rsyslog options on CentOS 6.5

### ISSUE THREAD

**Issue by mmarseglia** [saz/puppet-rsyslog#148]
Hi,

  I have a problem using the system utility `/bin/logger` when rsyslog is started with option -c4 as specified in /etc/sysconfig/rsyslog.  I can only get `/bin/logger` to work if I set compatibility level to 3 by commenting out the RSYSLOGD_OPTIONS line in `/etc/sysconfig/rsyslog`

  It appears the template rsyslog_default.erb looks at the rsyslog release and adds option -c4 by default with no way to change it.

```
<% if @rsyslog_version and @rsyslog_version.split('.')[0].to_i < 7 -%>
# Debian, Ubuntu
RSYSLOGD_OPTIONS="-c4"
```

  I see `$custom_params` has a TODO next to it.  Is it intended to use ` $custom_params` in the template to make it more flexible?

**Comment by saz** [comment]
If you want to send in a pull request, adding custom params for defaults/sysconfig files, I'll be happy to merge it!

**Comment by saz** [comment]
This is fixed in master and will be released soon.
