### ISSUE TITLE
Rsyslog client adds config to log remotely even when log_remote is set to false

### ISSUE THREAD

**Issue by jasonedwardsleadx** [saz/puppet-rsyslog#150]
I am using this module in my environment and have specifically set log_remote to false but it is still adding the following line to /etc/rsyslogd/client.conf:

\*.\* @@log:514;RSYSLOG_ForwardFormat

I receive no logs in my local log files namely /var/log/messages unless I comment out this line. Problem is when I do comment it out puppet puts it back again on subsequent puppet runs.
Can you advise?

**Comment by jasonedwardsleadx** [comment]
Follow up - If I change this to UDP instead then it work for several minutes then stops working again until a restart of the service.

**Comment by saz** [comment]
Do not set ```remote_servers``` and make sure, that ```log_remote``` is set to ```false```.

If you want local logging, you have to set ```log_local``` to ```true```

**Comment by jasonedwardsleadx** [comment]
Thank-you for your reply. I must admit I came to the same conclusions not long after I left this and forgot to return and close it off.
