### ISSUE TITLE
No ability to bind to a specific IP address

### ISSUE THREAD

**Issue by stephanmitchev** [saz/puppet-rsyslog#157]
It would have been nice to be able to define the hostname to bind when running a server. In many cases when we run rsyslog as a client only, we have apps that try to connect to localhost via UDP. So we have to use something like:

    rsyslog::modules:
      - "$ModLoad imuxsock # provides support for local system logging"
      - "$ModLoad imklog   # provides kernel logging support (previously done by rklogd)"
      - "#$ModLoad immark  # provides --MARK-- message capability"
      - "$ModLoad imudp    # Provides UDP Support"
      - "$UDPServerAddress localhost  # binds to localhost only"
      - "$UDPServerRun 514            # Sets the server port"

It would be great to be able to declare rsyslog::server {} with host and port parameters.

**Comment by saz** [comment]
It's possible for the server with ```address``` and ```port```.

It's also possible for the client with the ```listen_localhost``` parameter.

I think it's ```listen_localhost``` what you're looking for: running a central rsyslog server and some clients should act as local syslog server for some applications, but still forward messages to the central server.
