### ISSUE TITLE
puppet-rsyslog populates client.conf with deprecated parameters even though rsyslog v7 and above support them.

### ISSUE THREAD

**Issue by bschonec** [saz/puppet-rsyslog#158]
In ../templates/client.conf.erb, puppet-rsyslog populates /etc/rsyslog.d/client.conf with old style parameters rather than the newer style:

# Everybody gets emergency messages
*.emerg       :omusrmsg:*

In Rsyslog documentation, http://www.rsyslog.com/doc/v8-stable/compatibility/v7compatibility.html, the notes say that rsyslog version 7 supports omusrmsg rulesets.  puppet-rsyslog checks for version 8 or higher instead of version 7.  It populates version 7 rsyslog configuration files with older style parameters. 

# Everybody gets emergency messages
<% if @rsyslog_version and @rsyslog_version.split('.')[0].to_i >= 8 -%>
*.emerg       :omusrmsg:*
<% else -%>
*.emerg       *
<% end -%>

I recommend that the version checked is "7" rather than "8" so that users of rsyslog v7 and higher aren't nagged with:

please change syntax, 'cron' will not be supported in the future [try http://www.rsyslog.com/e/2184 ]

**Comment by saz** [comment]
This is fixed in the current master and will be released soon
