### ISSUE TITLE
librelp not available for RHEL 5

### ISSUE THREAD

**Issue by tduvally** [saz/puppet-rsyslog#162]
It looks like there is no librelp package for RHEL 5. This mean that this module is only compatible with RHEL => 6. Same for CentOS 5.

RHEL 5 is old, but still supported for a few more years.

**Comment by ekini** [comment]
It's present in official repository

    Name       : librelp
    Arch       : x86_64
    Version    : 1.2.5
    Release    : 1.el5.centos
    Size       : 55 k
    Repo       : rsyslog
    Summary    : The Reliable Event Logging Protocol library
    URL        : http://www.rsyslog.com/

See also #161

**Comment by saz** [comment]
This should be resolved with release 4.0.0
