### ISSUE TITLE
$ModLoad is outdated method for loading modules

### ISSUE THREAD

**Issue by gjngeldenhuis** [saz/puppet-rsyslog#167]
The rsyslog recommended way to load modules is module(load="imklog") not $ModLoad any more. $ModLoad is only for backwards compatibility and the expectation is that puppet module will follow best practices.

**Comment by seefood** [comment]
Also, I added an /etc/rsyslog.d/ file to re-enable immark and imklog. @saz is there a reason why it is not configurable by the module? should I submit a PR?

**Comment by saz** [comment]
@gjngeldenhuis Feel free to send me a PR for this
@seefood Would be great!

**Comment by gjngeldenhuis** [comment]
@saz I have ended up using https://forge.puppet.com/crayfishx/rsyslog which better supports the modern options.
