### ISSUE TITLE
How to set preserve_fqdn and etc...

### ISSUE THREAD

**Issue by samuraiii** [saz/puppet-rsyslog#169]
Hello I didint found any way to ser rsyslog main varibles... I feel so dumb that i cant figure this out...

When using
role::syslog{

class{ 'rsyslog':
preserve_fqdn=>true;
'rsyslog::server':
...
}
}
I get that rsyslog is double declarated.
Any help would be nice to get me from insanity.

**Comment by xaniasd** [comment]
You can set the variable through hiera

```rsyslog::preserve_fqdn: true```

**Comment by samuraiii** [comment]
Thank you, but I moved forward to logstash.
