### ISSUE TITLE
rsyslogd-2039: Could no open output pipe '/dev/xconsole': No such file or directory [try http://www.rsyslog.com/e/2039 ]

### ISSUE THREAD

**Issue by greenaar** [saz/puppet-rsyslog#174]
Looks like 

daemon._;mail._;\
        news.err;\
        _.=debug;_.=info;\
        _.=notice;_.=warn       |/dev/xconsole

Gets added automatically when using client => log_local.  Can you either comment it out or expose a method to disable it?  None of my servers have /dev/xconsole available, so i'll always get this error.

**Comment by saz** [comment]
Don't hesitate to send in a PR for this ;)

**Comment by jurim76** [comment]
Please just disable this xconsole section.  Who need this? Absolutely useless for production environment.

**Comment by saz** [comment]
I've added a new parameter "disable_xconsole" to disable those lines (it's false by default!)
