### ISSUE TITLE
how to use the module in profile for rsyslog relay chain?

### ISSUE THREAD

**Issue by walidshaari** [saz/puppet-rsyslog#182]
I have a use case where several compute nodes forward to one central node, then again this central node relays all these logs to other log analyzers (e.g. splunk, elk, SOC siem), due to the use of Rulesets the logs forwarded to the central server nodes are not relayed to the log analytical nodes on a different server, one way to fix this is to remove/comment out lines related to ruleset and its binding (this is working for me), however i imagine this was done on purpose, is there another way?  the use of RSYSLOG::SERVER custom_config is not possible also unless i add the new config template under the base module, i am trying to use the module in a profile that customize our use case. or is that fine?

**Comment by saz** [comment]
This is now possible starting with release 4.0.0 (search for ```relay_server```)
