### ISSUE TITLE
Default package_status shouldn't be latest

### ISSUE THREAD

**Issue by ardichoke** [saz/puppet-rsyslog#188]
It is my understanding, from talking to various Puppetlabs employees at a few conferences, that using ensure => latest is frowned upon, because it causes excessive traffic as puppet then goes out and checks the package repositories every time it is run. It would probably be better to have the default package_status be "installed" and let people decide they want to go against best practices on their own.

**Comment by szponek** [comment]
+1
People could still force that with rsyslog::package_status: 'installed' in their hiera if they want (as I currently have to for it to work the other/proper way around).

**Comment by ardichoke** [comment]
That is what I did as well, was just filing a report as it seems the default value should follow best practices.

**Comment by saz** [comment]
Just send in a PR and I'll be happy to merge it. Also a warning message inside documentation would be great to inform people about this change

**Comment by saz** [comment]
Resolved with release 4.0.0
