### ISSUE TITLE
condition inside default template is always evaluated to true

### ISSUE THREAD

**Issue by thbounzer** [saz/puppet-rsyslog#192]
The default rsyslog file is always including Redhat family despite os family being different. #191

**Comment by szponek** [comment]
#198 - should resolve that

**Comment by thbounzer** [comment]
Also #191 , I submitted it weeks ago

**Comment by szponek** [comment]
Oh, right. My vision must be degrading, I haven't noticed your PR before.

**Comment by saz** [comment]
#191 is merged now.
