### ISSUE TITLE
rsyslog_version should use rsyslog_package_name

### ISSUE THREAD

**Issue by ardichoke** [saz/puppet-rsyslog#193]
If you change the default rsyslog_package_name (for instance, when installing rsyslog7 in RHEL6), it breaks the templates as hardcoded package names are used to define the rsyslog_version fact resulting in that fact being null. When the template attempts to do a versioncmp to see if it should enable RELP, it gets a null which results in a nil:nilClass error and the template fails to parse.

**Comment by saz** [comment]
This should be fixed in version 4.0.0
