### ISSUE TITLE
incorrect scope of log_local_custom

### ISSUE THREAD

**Issue by shaunrampersad** [saz/puppet-rsyslog#194]
Hi

The scope is incorrect for log_local_custom within the local.conf.erb. 

`<% if @log_local_custom -%>
 # Custom fragment
 <%= @log_local_custom %>
<% end -%>`

It should read
`<% if scope.lookupvar('rsyslog::client::log_local_custom') -%>
 # Custom fragment
 <%= scope.lookupvar('rsyslog::client::log_local_custom') %>
<% end -%>
`

Thanks

**Comment by saz** [comment]
Should be fixed in release 4.0.0
