### ISSUE TITLE
Rpm Failure

### ISSUE THREAD

**Issue by jsmelser** [saz/puppet-rsyslog#203]
Mar 28 14:15:36 prvlopsdba01 puppet-agent[8370]: Could not update: Execution of '/usr/bin/yum -d 0 -e 0 -y list false' returned 1: Error: No matching Packages to list
Mar 28 14:15:36 prvlopsdba01 puppet-agent[8370]: (/Stage[main]/Rsyslog::Install/Package[false]/ensure) change from absent to latest failed: Could not update: Execution of '/usr/bin/yum -d 0 -e 0 -y list false' returned 1: Error: No matching Packages to list
Mar 28 14:15:36 prvlopsdba01 puppet-agent[8370]: (/Stage[main]/Rsyslog::Config/File[/etc/sysconfig/rsyslog]) Dependency Package[false] has failures: true
Mar 28 14:15:36 prvlopsdba01 puppet-agent[8370]: (/Stage[main]/Rsyslog::Config/File[/etc/sysconfig/rsyslog]) Skipping because of failed dependencies
Mar 28 14:15:36 prvlopsdba01 puppet-agent[8370]: Finished catalog run in 4.79 seconds

**Comment by saz** [comment]
Please try the newest release and open this issue again, if the problem still exists.
