### ISSUE TITLE
Upgrading from old version of rsyslog causes invalid syntax for client

### ISSUE THREAD

**Issue by joshbeard** [saz/puppet-rsyslog#208]
For example, if the current, stock installed version of rsyslog is 5.x.x, the fact `rsyslog_version` will report it as such, causing the configuration to use the "old" syntax for `emerg` (`*` vs `:omusrmsg:*`)  (see https://github.com/saz/puppet-rsyslog/blob/master/templates/client/local.conf.erb#L103) .  This occurs even if `package_status` is latest and rsyslog 8.x gets installed.  As a result, rsyslog fails to start.  A second Puppet run is needed so that the `rsyslog_version` reports the newly installed version and uses the proper syntax.

**Comment by saz** [comment]
This should be fixed with release 4.0.0
