### ISSUE TITLE
Release new forge version

### ISSUE THREAD

**Issue by rnelson0** [saz/puppet-rsyslog#212]
The current version on the forge, 3.5.1, is now 13 months old. Please release a new version, 3.6.0 or 4.0.0, so users can leverage the new fixes and features without pulling from a specific commit or from HEAD.

**Comment by seanscottking** [comment]
👍  and 😉  @rnelson0

**Comment by robert4man** [comment]
Specifically, I'm looking for a fix to the rsyslog_version issue when using rsyslog7 on RHEL6: #165, #193, #204 & pull request #187. I agree that using rsyslogd -v for the version fact probably makes more sense.

**Comment by rnelson0** [comment]
@saz Bump

**Comment by saz** [comment]
Finally! Please report any issues or comment on resolved issues if they can be closed. Thanks!
