### ISSUE TITLE
imjournal rate limiting support breaks rsyslog

### ISSUE THREAD

**Issue by mmarseglia** [saz/puppet-rsyslog#215]
The imjournal rate limiting directives added in #200 breaks rsyslog in the default configuration because the module "imjournal" is not loaded.  The "imjournal" module is not loaded by default.

CentOS 6.8
rsyslogd 5.8.10, compiled with:
	FEATURE_REGEXP:				Yes
	FEATURE_LARGEFILE:			No
	GSSAPI Kerberos 5 support:		Yes
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	Runtime Instrumentation (slow code):	No

> [root@ ~]# service rsyslog restart
Shutting down system logger: Aug  2 14:29:47  kernel: Kernel logging (proc) stopped.
Aug  2 14:29:47  rsyslogd: [origin software="rsyslogd" swVersion="5.8.10" x-pid="24707" x-info="http://www.rsyslog.com"] exiting on signal 15.
                                                           [  OK  ]
Starting system logger:                                    [  OK  ]
[root@ ~]# Aug  2 14:29:47  kernel: imklog 5.8.10, log source = /proc/kmsg started.
Aug  2 14:29:47  rsyslogd: [origin software="rsyslogd" swVersion="5.8.10" x-pid="25258" x-info="http://www.rsyslog.com"] start
Aug  2 14:29:47  rsyslogd: rsyslogd's groupid changed to 4
Aug  2 14:29:47  rsyslogd-3003: invalid or yet-unknown config file command - have you forgotten to load a module? [try http://www.rsyslog.com/e/3003 ]
Aug  2 14:29:47  rsyslogd: the last error occured in /etc/rsyslog.conf, line 41:"$ImjournalIgnorePreviousMessages off"
Aug  2 14:29:47  rsyslogd-3003: invalid or yet-unknown config file command - have you forgotten to load a module? [try http://www.rsyslog.com/e/3003 ]
Aug  2 14:29:47  rsyslogd: the last error occured in /etc/rsyslog.conf, line 43:"$imjournalRatelimitInterval 600"
Aug  2 14:29:47  rsyslogd-3003: invalid or yet-unknown config file command - have you forgotten to load a module? [try http://www.rsyslog.com/e/3003 ]
Aug  2 14:29:47  rsyslogd: the last error occured in /etc/rsyslog.conf, line 45:"$imjournalRatelimitBurst 20000"
Aug  2 14:29:47  rsyslogd-2124: CONFIG ERROR: could not interpret master config file '/etc/rsyslog.conf'. [try http://www.rsyslog.com/e/2124 ]

**Comment by saz** [comment]
Does this error still occur with version 4.0.0?

**Comment by benohara** [comment]
Yes, still occours with 4.0.1

**Comment by phamp008** [comment]
How do I get rid of those entries /etc/rsyslog.conf on Enterprise Linux 6 ? 

> $ImjournalIgnorePreviousMessages off

> $imjournalRatelimitInterval 600

> $imjournalRatelimitBurst 20000

I also notice captalized "I" for imjournalIgnorePreviousMessages .

Can we pass parameters as 'undef' for those 3 ?

**Comment by phamp008** [comment]
This issue is still there for Linux EL6 with 4.0.0

**Comment by antaflos** [comment]
Also problematic on Ubuntu 12.04 and 14.04.

**Comment by esalberg** [comment]
Same - RHEL6 with v4.0.2

I tried setting the following, but it did not help:
      class { 'rsyslog':
        im_journal_ratelimit_interval       => undef,
        im_journal_ratelimit_burst          => undef,
        im_journal_ignore_previous_messages => undef,
      }

I'm going to patch it myself by adding an option to rsyslog::client directly - I can put in a PR for that if it's a helpful fix (I don't know if you'd prefer to fix it a different way).

**Comment by jpmadden3** [comment]
I am new to this world and communicating not sure what undefined should do to rsyslog.conf file - but in a RHEL 6.8, rsyslog v5.8 environment the imjournal attributes still show up in rsyslog.conf file - not sure how I can help other to point out that it still seems to be a problem.

I believe I will try to upgrade rsyslog to be above the required threshold of 7.x to see if this works that way - different question then.  Thanks for the attention to this
