### ISSUE TITLE
Module override normal behaviour under Red Hat 7: no log under /var/log

### ISSUE THREAD

**Issue by mimmus** [saz/puppet-rsyslog#219]
On Red Hat 7, using default values, it changes normal behaviour of OS: it doesn't log anything under /var/log! No messages, no secure, no maillog: nothing! Probably it uses only journal.
It would be great if this module:
    - doesn't override default Red Hat config
    - or at least provide a sufficient set of default options

**Comment by saz** [comment]
It's a decision decision. Everything should be logged to a central server. If you want local logging enabled, just set log_local to true.
