### ISSUE TITLE
the last error occured in /etc/rsyslog.d/client.conf, line 43:" undef"

### ISSUE THREAD

**Issue by yackushevas** [saz/puppet-rsyslog#220]
Hello.
I have error in logs:

rsyslogd: the last error occured in /etc/rsyslog.d/client.conf, line 43:" undef"
rsyslogd: warning: selector line without actions will be discarded

cat -n /etc/rsyslog.d/client.conf | tail -2
    42   # Custom fragment
    43   undef

my configs:

class rsyslog {
  class { 'rsyslog::client':
      log_remote     => true,
      remote_type    => 'tcp',
      log_local      => true,
      log_auth_local => false,
      server         => 'some_ip',
      port           => '514',
      remote_forward_format   => 'RSYSLOG_SyslogProtocol23Format',
  }
}

How i can remove option "custom fragment"?

P.S. CentOS 6.7, puppet 3.8

**Comment by darkpixel** [comment]
Yeah, I get that too.  client.conf ends with:
```
 # Custom fragment
 undef
```

I edited the local.conf.erb file in the module and ripped out the line:
```
 <%= scope.lookupvar('rsyslog::client::log_local_custom') %>
```

**Comment by saz** [comment]
Is this error occurring with the newest release? 

Sent using Boxer

On 1 Sep 2016 9:22 PM, "Aaron C. de Bruyn" <notifications@github.com> wrote:

Yeah, I get that too. client.conf ends with:

# Custom fragment undef 

I edited the local.conf.erb file in the module and ripped out the line:

<%= scope.lookupvar('rsyslog::client::log_local_custom') %>

**Comment by darkpixel** [comment]
I installed about 2 hours ago using ```puppet module install saz-rsyslog```

```
root@tetrad:~# puppet module list | grep -i syslog
├── saz-rsyslog (v4.0.0)
root@tetrad:~# 
```
