### ISSUE TITLE
Ability to log locally to allow kernel.*  to write to /dev/console

### ISSUE THREAD

**Issue by phamp008** [saz/puppet-rsyslog#222]
Hello,
We are using rsyslog client with log locally.  We notice that default template for RedHat style with
# kernel.\*       /dev/console

Is there a way for us to uncomment this out without modify this template ?

**Comment by bschonec** [comment]
You could use the rsyslog::client::log_local_custom argument.  I don't know if that's the preferred method.  I'm struggling with the same sort of thing.  I need to log to separate local files but am unsure the best way to do so.

log_local_custom => ['kernel.* /dev/console',]

should do the trick.

**Comment by phamp008** [comment]
@bschonec  thanks !  I was able to use this successfully
