### ISSUE TITLE
Add support for --MARK-- message compatibility

### ISSUE THREAD

**Issue by bschonec** [saz/puppet-rsyslog#226]
On all my servers I use (and need) the --MARK-- message sent to syslog every XXX minutes.  Currently, the --MARK-- functionality is commented out in the $modules array and there is no way to turn on --MARK-- functionality.

A hackish way to allow marking would be to add a new parameter ($mark) that would be set to true or false.  Here's how I see this working without ripping out the current values of $modules array:

class rsyslog::params {
  $mark = false

  $enable_mark = $mark ? {
    false => "#",
    true => "",
  }

$modules = [ "${enable_mark}$ModLoad immark  # provides --MARK-- message capability", ..., ..., ...]

This is a bit hackish but probably the least disruptive.

Essentialy what this does is comment out the $ModLoad line if $mark=false and "uncomment" the line if $mark=true.

Thoughts?

**Comment by saz** [comment]
There is a parameter to pass in modules.
class { 'rsyslog':
  modules => ['$ModLoad imuxsock', '$ModLoad imklog', '$ModLoad immark']
}

Isn't this working for you?

**Comment by saz** [comment]
btw, I know, the module handling might be improved, but as long as there is no pull request, I need to find time to clean this up.

**Comment by bschonec** [comment]
I'm actually working on this right now.

**Comment by seefood** [comment]
I did:
```puppet
  file { '/etc/rsyslog.d/markklog.conf':
    owner   => 'root',
    group   => 'root',
    mode    => '0600',
    notify  => Service['rsyslog'],
    content => '
      module(load="imklog")
      module(load="immark")'
  }
```
because rsyslog complained `$ModLoad` syntax was phased out.
