### ISSUE TITLE
Allow remote_servers => [{ pattern }] to accept arrays and output on multiple lines

### ISSUE THREAD

**Issue by bschonec** [saz/puppet-rsyslog#227]
I have quite a few patterns that I use for external logging.  The module globs them all together into one line such as:

class { 'rsyslog::client':
  remote_servers => [
    {
      host      => 'splunk', 
      pattern   => 'authpriv.\* cron.\* _.emerg *.info;mail.none;authpriv.none;cron.none local7._ mail.\* uucp,news.crit',
    },
  ]
}

This makes one long line:

authpriv.\* cron.\* _.emerg *.info;mail.none;authpriv.none;cron.none local7._ mail.\* uucp,news.crit @splunk:514

It'd be more readable if the patterns were on separate lines.

**Comment by saz** [comment]
It should be no problem to just add more values to the array.
Instead of defining everything in one hash, just use multiple with the same value for ```host```
