### ISSUE TITLE
What's the best way to log to local files?

### ISSUE THREAD

**Issue by bschonec** [saz/puppet-rsyslog#230]
I need to log different syslog levels to different files.  I see $log_local_custom in rsyslog::client but that only allows for a single entry.

I need:

kernel.debug /var/log/kernel.debug
user.log /var/log/user.log

What's the best way to accomplish this?

**Comment by saz** [comment]
One way of solving this:
```
class { 'rsyslog::client':
  log_local_custom => template('path/to/a/template')
}
```
If this won't help you, feel free to send in a PR, which adds the possibility of passing in an array of lines or a string.
