### ISSUE TITLE
Duplicate Declaration Class[Rsyslog] with The Foreman as ENC during catalog compilation

### ISSUE THREAD

**Issue by rglaue** [saz/puppet-rsyslog#237]
I have been experiencing a duplicate declaration error when The Foreman builds a catalog for a node that declares rsyslog::client before rsyslog.

A very long and detailed discussion is here:
Issue with module from forge - Duplicate declaration Class[Rsyslog]
https://groups.google.com/d/topic/puppet-users/0JHrMGuo8YQ/discussion

We finally came to the conclusion that under certain and uncommon circumstances The Foreman can sometimes build a catalog in which subclasses can be declared before their parent class.
In general practice with other puppet modules this is not an issue. But it is an issue for saz-rsyslog.

In review of the saz-rsyslog module version 4.0.3 it was discussed ...
"... the module violates the DSL specifications by having rsyslog::client inherit from a parameterized class at all.  In practice, that combination normally works as desired, provided that any parameterized direct declaration of the base class is evaluated before all declarations of the subclass.  Evaluation-order dependencies such as this can be very difficult to deal with, and should be avoided at all costs. ..."

I understand the practice is to write in the class declarations into the site.pp file. However, when using The Foreman, the administrator does not write any files, and all declarations compiled in the catalog are generated dynamically. Thus the admin does not have control over the order.

I also understand that The Foreman _may_ have an issue in declaring a subclass before its parent class, and this should too be addressed. I will look into posting a related issue with The Foreman.

I am humbly requesting that the inheritance issue with the saz-rsyslog be addressed.
I would greatly appreciate it.
I really like the saz modules.
Thank you.
-RG

**Comment by rglaue** [comment]
Here is a conclusion from The Foreman group discussion.

https://groups.google.com/d/topic/foreman-users/k0JgABtszdU/discussion
> This is an issue with the format of the ENC YAML used between Foreman
> and Puppet, and is best fixed in the module. 
> 
> The list of classes is given as a hash/dictionary and so has no 
> particular order defined - it's down to the Puppet master/server to 
> iterate over it, and it probably does so in no particular order. It 
> isn't under Foreman's control.

**Comment by saz** [comment]
As @rnelson0 is mentioning during the discussion, I'm absolutely happy about a pull request.

Anyways, as far as I can see:
rsyslog::client is inheriting from rsyslog just to get the right value for the name of the client config snippet. Which might be a good thing, but not really necessary...

Same situation with rsyslog::server

Moving those parameters from rsyslog to rsyslog::client and rsyslog::server and then including rsyslog might be working as expected, but I need to check that.

**Comment by saz** [comment]
As this is hard for me to reproduce, can you try it with the current master version, if it's working for you now?

I'm aware that the database configuration needs fixing, but this is a bigger change...

**Comment by rglaue** [comment]
I installed the module from master as of 01:49 GMT, and I am receiving this error on the nodes:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: Package[true] is already declared in file /etc/puppet/environments/production/modules/rsyslog/manifests/install.pp:18; cannot redeclare at /etc/puppet/environments/production/modules/rsyslog/manifests/install.pp:25 on node server1.mydomain.example.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by saz** [comment]
That one's easy :-)

Do not set 'true' as the value for gnutls_package_name, relp_package_name and rsyslog_package_name. Those params are expecting a package name.

Is there any reason for setting those params at all? As long as you're not relying on non-distro packages, everything should be working.

**Comment by rglaue** [comment]
I want to set those parameters. I am setting them to "false" in all production nodes. (setting it as true in my previous post was just for testing on a particular testing node)
I don't want the rsyslog module to manage any packages. When it was on for CentOS5 nodes, it wanted to install rsyslog5 (not rsyslog) and a relp package that was incompatible with each other. I assume if I were to even set the package names I wanted, I would still have this issue because I would be setting the parameters.
I'm also setting preserve_fqdn to "true" in all nodes in the parent Rsyslog class.

**Comment by saz** [comment]
It's failing, because all of those parameters are set to true.
This will create 3 different package resources with the name set to 'true' which is an error in puppet.

Or I'm getting you wrong. Then please explain it a little bit more to me :-)

**Comment by saz** [comment]
As can be seen by this line:
```Duplicate declaration: Package[true] is already declared in file ```

**Comment by rglaue** [comment]
Sorry about the misunderstanding.
I have moved the rsyslog (pulled from master) puppet module to a production subnet I have been having issues with. I triggered the class declaration ordering issue in puppet as I have described before, and the Duplicate declaration Class[Rsyslog] error is not occurring. So this issue has been resolved.

/var/lib/puppet/yaml/foreman/server1.mydomain.example.net.yaml
```
...snip...
  rsyslog:
    gnutls_package_name: false
    preserve_fqdn: true
    relp_package_name: false
    rsyslog_package_name: false
  rsyslog::client:
    log_local: false
    remote_type: udp
    server: syslogserver.mydomain.example.net
...snip...
```

/var/lib/puppet/yaml/node/server1.mydomain.example.net.yaml
```
...snip...
    "rsyslog::client": 
      remote_type: udp
      server: syslogserver.mydomain.example.net
      log_local: false
    ntp: 
      server_list: 
        - "ntpserver.mydomain.example.net"
    rsyslog: 
      relp_package_name: false
      preserve_fqdn: true
      gnutls_package_name: false
      rsyslog_package_name: false
...snip...
```

Previously, with this output, the node received a 400 Bad Server ... Duplicate declaration Class[Rsyslog] ... error. But with the new saz-rsyslog update pulled from master, the node performs an agent update without error.

Thank you!

**Comment by saz** [comment]
Awesome. I'll create a new release as soon as possible. Thanks for your help!

**Comment by saz** [comment]
Should be working with the newest release v5.0.0

**Comment by rglaue** [comment]
Yes, it works. Thanks.
