### ISSUE TITLE
question related to [log_filters](https://github.com/saz/puppet-rsyslog/pull/209) change

### ISSUE THREAD

**Issue by bilsch** [saz/puppet-rsyslog#242]
I'm having issues getting the log_filters to work properly - not sure how else to ask for input on this one.

hiera config:
```
rsyslog::client::log_filters:
  'foo':
    expression: '$programname == "foo"'
    action: /var/log/foo.log
```

puppet output
```
==> app1: Error: Evaluation Error: Error while evaluating a Function Call, Failed to parse template rsyslog/client/config.conf.erb:
==> app1:   Filepath: /tmp/vagrant-puppet/environments/production/modules/rsyslog/templates/client/config.conf.erb
==> app1:   Line: 22
==> app1:   Detail: no implicit conversion of String into Integer
==> app1:  at /tmp/vagrant-puppet/environments/production/modules/rsyslog/manifests/client.pp:67:21 on node app1
```

I am pretty sure this is the erb section:

```
<% scope.lookupvar('rsyslog::client::log_filters').each do |log_filter| -%>
if <%= log_filter['expression'] %> then <%= log_filter['action'] %>
<% end -%>
```

Am I defining that right? I read that as taking all elements of the log_filters hash discarding the key name - only using expression and action of each key

This is using `v4.0.3` tag / release

**Comment by nexecook** [comment]
It is misleading, but `rsyslog::client::log_filters` expects an array, not sure why the readme mentions using an hash.

```
rsyslog::client::log_filters:
  - expression: '$programname == "foo"'
    action: /var/log/foo.log
```

**Comment by saz** [comment]
I've added an example to the README.
https://github.com/saz/puppet-rsyslog#log-filter-example-for-hiera

Let me know, if there is still more informationen needed.
