### ISSUE TITLE
Upgrading from 4.0.3 to 5.0.0 does not delete old rsyslog.d/client.conf

### ISSUE THREAD

**Issue by rglaue** [saz/puppet-rsyslog#246]
I just upgraded from 4.0.3 to 5.0.0

I was using the two classes: `rsyslog`, and `rsyslog::client`
This managed two files: `/etc/rsyslog.conf`, and `/etc/rsyslog.d/client.conf`

After upgrading to 5.0.0, a `puppet agent -t` run creates a new client config file  `/etc/rsyslog.d/00_client.conf` , but does not delete the previously managed `/etc/rsyslog.d/client.conf`. So both files are existing in `rsyslog.d/` now.

Running a diff on the two files yields no differences. And rsyslog does not appear to be having an issue with both files existing. So this does not break rsyslog. However, I would assume problems would start arising once new changes are made to `rsyslog::client`, and these two files begin to differ.

Can the older file be removed?
Or let the behavior be that when `split_config=false` then `rsyslog::client` only manages the client config as `/etc/rsyslog.d/client.conf`, and when `true` performs as documented?

**Comment by saz** [comment]
This is just a rename of the config file. 


Can you show the parameters passed to both classes? 


Sent using Boxer

On 2 Dec 2016 5:19 PM, rglaue <notifications@github.com> wrote:

I just upgraded from 4.0.3 to 5.0.0

I was using the two classes: rsyslog, and rsyslog::client
This managed two files: /etc/rsyslog.conf, and /etc/rsyslog.d/client.conf

After upgrading to 5.0.0, a puppet agent -t run creates a new client config file /etc/rsyslog.d/00_client.conf , but does not delete the previously managed /etc/rsyslog.d/client.conf. So both files are existing in rsyslog.d/ now.

Running a diff on the two files yields no differences. And rsyslog does not appear to be having an issue with both files. So this does not break rsyslog. However, I would assume problems would start arising once new changes are made to rsyslog::client, and these two files begin to differ.

Can the older file be removed.
Or let the behavior be that when split_config=false then rsyslog::client only manages the client config as /etc/rsyslog.d/client.conf, and when true performs as documented?

**Comment by rglaue** [comment]
parameters passed to both classes:
```
class { 'rsyslog':
    preserve_fqdn        => true,
    gnutls_package_name  => false,
    relp_package_name    => false,
    rsyslog_package_name => false
}
class { 'rsyslog::client':
    log_local            => true,
    remote_type          => udp,
    server               => syslog.example.com
}
```

And here is the output on a client node:
```
[root@server1 ~]# ls -l /etc/rsyslog.d/
-rw-------.  1 root root 1542 Dec  2 10:04 client.conf

# Performed puppet module upgrade from 4.0.3 to 5.0.0

[root@server1 ~]# puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: NetworkManager is not running.
Info: Caching catalog for server1.example.com
Info: Applying configuration version '1480694817'
Notice: /Stage[main]/Rsyslog::Client/Rsyslog::Snippet[00_client]/File[/etc/rsyslog.d/00_client.conf]/ensure: created
Info: /Stage[main]/Rsyslog::Client/Rsyslog::Snippet[00_client]/File[/etc/rsyslog.d/00_client.conf]: Scheduling refresh of Class[Rsyslog::Service]
Info: Class[Rsyslog::Service]: Scheduling refresh of Service[rsyslog]
Notice: /Stage[main]/Rsyslog::Service/Service[rsyslog]: Triggered 'refresh' from 1 events
Notice: Finished catalog run in 1.14 seconds

[root@server1 ~]# ls -l /etc/rsyslog.d/
-rw-------.  1 root root 1542 Dec  2 10:07 00_client.conf
-rw-------.  1 root root 1542 Dec  2 10:04 client.conf
```

**Comment by walkamongus** [comment]
I just ran into this issue as well

**Comment by corey-hammerton** [comment]
Have you tried the `purge_rsyslog_d` parameter of Class["Rsyslog"]?

**Comment by walkamongus** [comment]
This would work as long as it can be done safely. In my situation, this is an unknown. There are a few  workarounds and the major version bump indicates backwards incompatibility. Based on that, it seems reasonable that this could be closed as a non-issue but I'll leave that up to @rglaue.

**Comment by rglaue** [comment]
On the merits of the issue alone, I would agree with @walkamongus . However, then the resolution is not a code change, but a documentation change. Documentation related to upgrade incompatibility warnings. The system admin needs to be aware of this before they upgrade.

I had deployed the checked-out code at HEAD a week or so before 5.0.0 release to test a resolution to a previous submitted bug. This issue did not pop up in that test. So it is an unexpected issue.
If the documentation can be added to warn of this upgrade and version incompatibility issue, then it would be satisfactory to resolve the issue.

For me, I'll have to go through 300+ servers to perform a cleanup. The *undocumented* `purge_rsyslog_d` parameter is too forceful. For example, we have services that log to local syslog, and the RPM drops an rsyslog configuration file in `/etc/rsyslog.d/` directory. So ... can't use the *undocumented*  `purge_rsyslog_d` parameter.

**Comment by saz** [comment]
I now this wasn't a good change and I'm sorry for any inconvenience. I'll try to release a fixed version tomorrow. 


Saz


Sent using Boxer

On 20 Dec 2016 8:46 PM, rglaue <notifications@github.com> wrote:

On the merits of the issue alone, I would agree with @walkamongus . However, then the resolution is not a code change, but a documentation change. Documentation related to upgrade incompatibility warnings. The system admin needs to be aware of this before they upgrade.

I had deployed the checked-out code at HEAD a week or so before 5.0.0 release to test a resolution to a previous submitted bug. This issue did not pop up in that test. So it is an unexpected issue.
If the documentation can be added to warn of this upgrade and version incompatibility issue, then it would be satisfactory to resolve the issue.

For me, I'll have to go through 300+ servers to perform a cleanup. The undocumented purge_rsyslog_d parameter is too forceful. For example, we have services that log to local syslog, and the RPM drops an rsyslog configuration file in /etc/rsyslog.d/ directory. So ... can't use the undocumented purge_rsyslog_d parameter.
