### ISSUE TITLE
More control over files for network input modules - ruleset

### ISSUE THREAD

**Issue by ubellavance** [saz/puppet-rsyslog#251]
Hi,

I want to use this module to configure an rsyslog server that will receive logs from another rsyslog server, but I want to be able to choose where the locations of the files.  Through my testing, I figured out that this entry prevents me from doing that: `$InputTCPServerBindRuleset remote`. I understand that it makes input module use a nice ruleset that puts the logs in a organized manner, but when this file is there, I can't use filters.

If I'm missing something please let me know, otherwise it would be nice to have a simple option to enable this ruleset for the input modules or not.

**Comment by ubellavance** [comment]
Would it make sense to create a new variable, that would default to false, and when set to true, would not set the BindRuleset  to the InputServers?

**Comment by saz** [comment]
Fixed in current master
