### ISSUE TITLE
turn off imjournal.state file by parameter

### ISSUE THREAD

**Issue by seefood** [saz/puppet-rsyslog#252]
Howdie,

I'm running ossec-hids on my production servers and since switching to RHEL7 and systemd, it started complaining /var/lib/rsyslog/imjournal.state is owned by root and has modifiers 666. I'm not sure it's a real security hole (AFAIG it's only eritten but never read by rsyslogd) but still, these permissions are both weird and unchangable and I get (false?) alarms because of it.

Can you/I add a parameter to turn it off in rsyslog::client? I don't mind patching this myself.

**Comment by saz** [comment]
As this file is not managed by this module, I think those permissions are set by rsyslog (not sure about that) and I don't think it's good to mess with those permissions in this module.

If you set ```rsyslog::im_journal_statefile``` to false (or undef), it might stop rsyslog from creating this file.
