### ISSUE TITLE
FileCreateMode

### ISSUE THREAD

**Issue by ubellavance** [saz/puppet-rsyslog#255]
Hi,

Is there a reason why this module overrides the FileCreateMode parameter (to 0600)? [rsyslog's default is 0644](
http://www.rsyslog.com/doc/rsconf1_filecreatemode.html).

Thanks,

**Comment by saz** [comment]
This is only done on RedHat and Suse systems. I don't know, if this is the default value on those distributions, but there is a parameter ```rsyslog::perm_file``` to change it.
As a change might introduce some unexpected access to log files, I'll stick with the current value
