### ISSUE TITLE
Puppet 3.5 fatal error

### ISSUE THREAD

**Issue by DamianZaremba** [saz/puppet-rsyslog#74]
Including rsyslog produces the following error on an agent run

``` puppet
# puppet agent -tv

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, Error from DataBinding 'hiera' while looking up 'rsyslog::rsyslog_package_name': uncaught throw :undefined_variable at /etc/puppet/environments/production/modules/rc/manifests/base.pp:2:1 on node puppet-03.****.****
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

The offending line in that file is

``` puppet
include rsyslog
```

**Comment by sendalot** [comment]
anyone a found a solution to this "NilClass" problem?

**Comment by perfecto25** [comment]
having same issue on PE 2015.3 (puppet server 4.2.1)

this is only for this node, other nodes are working. Hiera looks ok for this node as well, I can pull out values from hiera cmd line

root@ubudevbox:/etc/puppetlabs/code# puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, undefined method `empty?' for nil:NilClass at /etc/puppetlabs/code/environments/production/manifests/site.pp:43:1 on node ubudevbox
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
